"""Build auditable ColabFold-Multimer inputs for the corrected pMHC-II set.

The input is a mature HLA-DRA chain, a mature HLA-DRB1*15:01 chain, and the
full IEDB peptide separated by ColabFold's ``:`` chain delimiter.  This script
only prepares inputs; it never labels a prediction as experimental evidence.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "processed"
TEMPLATE = ROOT / "raw" / "rcsb_templates" / "8TBP.pdb"
AA3 = {
    "ALA": "A", "ARG": "R", "ASN": "N", "ASP": "D", "CYS": "C",
    "GLN": "Q", "GLU": "E", "GLY": "G", "HIS": "H", "ILE": "I",
    "LEU": "L", "LYS": "K", "MET": "M", "PHE": "F", "PRO": "P",
    "SER": "S", "THR": "T", "TRP": "W", "TYR": "Y", "VAL": "V",
}


def atom_sequences(path: Path) -> dict[str, str]:
    residues: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for line in path.read_text(errors="ignore").splitlines():
        if line[:6].strip() != "ATOM":
            continue
        chain = line[21].strip() or "_"
        key = (line[22:26].strip(), line[26].strip(), line[17:20].strip())
        if key not in residues[chain]:
            residues[chain].append(key)
    return {
        chain: "".join(AA3.get(resname, "X") for _, _, resname in values)
        for chain, values in residues.items()
    }


def main() -> None:
    template = atom_sequences(TEMPLATE)
    dra = template["A"]
    drb = template["B"]
    if len(dra) < 150 or len(drb) < 150:
        raise ValueError("8TBP mature DRA/DRB chains were not parsed as expected")

    candidates = pd.read_csv(PROC / "pmhc_candidate_manifest.csv")
    candidates["peptide"] = candidates["peptide"].astype(str).str.upper()
    candidates["colabfold_sequence"] = candidates["peptide"].map(
        lambda peptide: f"{dra}:{drb}:{peptide}"
    )

    fasta_lines: list[str] = []
    manifest_rows: list[dict[str, object]] = []
    input_dir = PROC / "colabfold_inputs"
    input_dir.mkdir(exist_ok=True)
    for row in candidates.to_dict(orient="records"):
        candidate_id = str(row["candidate_id"])
        peptide = str(row["peptide"])
        sequence = f"{dra}:{drb}:{peptide}"
        header = (
            f">{candidate_id}|arm={row['arm']}|tier={row['evidence_tier']}|"
            f"iedb_epitope_id={row['iedb_epitope_id']}|peptide={peptide}"
        )
        fasta_lines.extend([header, sequence])
        (input_dir / f"{candidate_id}.fasta").write_text(
            f">{candidate_id}\n{sequence}\n", encoding="utf-8"
        )
        manifest_rows.append(
            {
                "candidate_id": candidate_id,
                "arm": row["arm"],
                "evidence_tier": row["evidence_tier"],
                "peptide": peptide,
                "peptide_length": int(row["peptide_length"]),
                "iedb_epitope_id": row["iedb_epitope_id"],
                "source_accession": row["source_accession"],
                "input_fasta": str(input_dir / f"{candidate_id}.fasta"),
                "colabfold_sequence": sequence,
                "chain_order": "HLA-DRA:mature HLA-DRB1*15:01:full IEDB peptide",
                "chain_lengths": f"{len(dra)}:{len(drb)}:{len(peptide)}",
                "template_pdb": "8TBP",
            }
        )

    (PROC / "pmhc_colabfold_inputs.fasta").write_text(
        "\n".join(fasta_lines) + "\n", encoding="utf-8"
    )
    manifest_df = pd.DataFrame(manifest_rows)
    manifest_df.to_csv(PROC / "pmhc_colabfold_manifest.csv", index=False)
    # ColabFold's batch API consumes the same two-column CSV schema used by
    # its notebook: id,sequence.  Keep candidate IDs unchanged so each output
    # directory and score file remains traceable to the evidence manifest.
    manifest_df[["candidate_id", "colabfold_sequence"]].rename(
        columns={"candidate_id": "id", "colabfold_sequence": "sequence"}
    ).to_csv(PROC / "pmhc_colabfold_batch.csv", index=False)
    metadata = {
        "input_format": "ColabFold multimer FASTA; colon-delimited chains",
        "template_pdb": "8TBP",
        "template_source": "https://www.rcsb.org/structure/8TBP",
        "template_chain_sequences": {
            "DRA": {"source_chain": "A", "length": len(dra)},
            "DRB1*15:01": {"source_chain": "B", "length": len(drb)},
        },
        "candidate_count": len(candidates),
        "batch_csv": "processed/pmhc_colabfold_batch.csv",
        "peptide_policy": "full IEDB peptide; no class-I 9-mer trimming",
        "status": "inputs_only; no coordinates generated by this script",
    }
    (PROC / "pmhc_colabfold_metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    print(f"wrote {len(candidates)} candidate inputs; DRA={len(dra)} aa, DRB={len(drb)} aa")


if __name__ == "__main__":
    main()
